// app/layout.tsx or app/auth/layout.tsx (depending on your folder structure)
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "bootstrap-icons/font/bootstrap-icons.css"
import { AuthContextProvider } from "@/contexts/Auth";
import { App } from "antd";

// Load Inter without variable (just className)
const inter = Inter({
  subsets: ["latin"],
  display: "swap", // optional
});

export const metadata: Metadata = {
  title: "Security PSA Vendor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} text-[#212121] bg-[#F9F9F9] antialiased`}>
        <App>
          <AuthContextProvider>
            {children}
          </AuthContextProvider>
        </App>
      </body>
    </html>
  );
}
